import os

css_file = r"C:\Users\rajti\Downloads\Projects\ChessVerse\src\index.css"

with open(css_file, 'a', encoding='utf-8') as f:
    f.write("\n\n/* Mobile responsive layout for Landing Page */\n")
    f.write(".landing-grid {\n")
    f.write("  display: grid;\n")
    f.write("  grid-template-columns: repeat(3, 1fr);\n")
    f.write("  gap: 2rem;\n")
    f.write("  max-width: 1100px;\n")
    f.write("  margin: 0 auto;\n")
    f.write("}\n")
    f.write(".landing-hero-title {\n")
    f.write("  font-size: 4.5rem;\n")
    f.write("  font-weight: 800;\n")
    f.write("  line-height: 1.1;\n")
    f.write("  letter-spacing: -0.03em;\n")
    f.write("  margin-bottom: 1.5rem;\n")
    f.write("  color: var(--text-main);\n")
    f.write("}\n")
    f.write(".landing-header {\n")
    f.write("  padding: 1.5rem 4rem;\n")
    f.write("  display: flex;\n")
    f.write("  justify-content: space-between;\n")
    f.write("  align-items: center;\n")
    f.write("}\n")
    f.write(".landing-nav {\n")
    f.write("  display: flex;\n")
    f.write("  align-items: center;\n")
    f.write("  gap: 3rem;\n")
    f.write("}\n")
    f.write(".landing-footer {\n")
    f.write("  padding: 3rem 4rem;\n")
    f.write("  background: #f1f5f9;\n")
    f.write("  border-top: 1px solid var(--border-color);\n")
    f.write("  margin-top: auto;\n")
    f.write("  display: flex;\n")
    f.write("  justify-content: space-between;\n")
    f.write("  align-items: center;\n")
    f.write("}\n")
    f.write(".landing-main {\n")
    f.write("  padding: 6rem 2rem;\n")
    f.write("}\n")
    
    f.write("\n@media (max-width: 768px) {\n")
    f.write("  .landing-grid {\n")
    f.write("    grid-template-columns: 1fr;\n")
    f.write("    gap: 1.5rem;\n")
    f.write("    padding: 0 1rem;\n")
    f.write("  }\n")
    f.write("  .landing-hero-title {\n")
    f.write("    font-size: 2.5rem;\n")
    f.write("  }\n")
    f.write("  .landing-header {\n")
    f.write("    padding: 1rem;\n")
    f.write("    flex-direction: column;\n")
    f.write("    gap: 1rem;\n")
    f.write("  }\n")
    f.write("  .landing-nav {\n")
    f.write("    display: none; /* Hide nav links on mobile for cleaner look */\n")
    f.write("  }\n")
    f.write("  .landing-footer {\n")
    f.write("    padding: 1.5rem;\n")
    f.write("    flex-direction: column;\n")
    f.write("    gap: 1.5rem;\n")
    f.write("    text-align: center;\n")
    f.write("  }\n")
    f.write("  .landing-main {\n")
    f.write("    padding: 3rem 1rem;\n")
    f.write("  }\n")
    f.write("}\n")

print("Added landing page CSS.")
